### ISSUE TITLE
update/register

### ISSUE THREAD

**Issue by rlawogns123** [1-hummingbird/front_starbucks_clone#22]
회원가입 페이지 수정

**Comment by yuseok-kim-edushare** [comment]
@rlawogns123 CI-CD 실패 보고 들어와서 댓글 남깁니다!



Run npm run build
  
> front_starbucks_clone@0.1.0 build
> next build
  ▲ Next.js 1[4](https://github.com/Spharos-Academy-5-Team-of-YuSeokKim/front_starbucks_clone/actions/runs/11032450203/job/30641365910#step:7:4).2.10
   Creating an optimized production build ...
Failed to compile.

**./src/app/(auth)/register/page.tsx**
경로의 파일을 컴파일 하는 데 실패 했데요.

Module not found: Can't resolve **'@/components/pages/register/RegisterStep1Form'**
요게 어떤 건지 못 알아 먹겠답니다.

한번 오류 수정해야 할 게 있는지
봐주시면 감사하겠습니다!
